### ISSUE TITLE
Complete colour sets not available

### ISSUE THREAD

**Issue by seagyn** [leadhomesa/oxygen#70]
All of the colours found in the design system are not available yet. Furthermore, they need have sane names that are easier to remember than light and lighter storm.

Colours can be found here: https://www.figma.com/file/bUBZY5aVyXYdedy2wCtDxr/Oxygen-Core?node-id=1%3A6500

The idea would be to have all colours with 1-6:

```
Coral1
Coral2
Coral3
Coral4
Coral5
```

With 2 always being the default `Coral`. In other words `Coral = Coral2 = '#FF6A70'`.

**Comment by fllprbt** [comment]
I am working on it. Are the top names in the image you provided ok (coral, storm, overcast)?

Do you need also a default Coral (without number) mapping to Coral 2?

**Comment by seagyn** [comment]
@fllprbt yeah, the names are good and you can map the default to colour 2 as per your example.

There are already colours which you can remove/replace with the new system.

**Comment by fllprbt** [comment]
I 've completed it, what should I do with colors that are not in the styles like (disabled, grey, gallery ...)?

**Comment by seagyn** [comment]
Thanks again!
